### ISSUE TITLE
Two-Sample T-test slow to configure with many perms

### ISSUE THREAD

**Issue by nicholst** [nicholst/SnPM-devel#11]
Two sample T-test, due to the while loop [here](https://github.com/nicholst/SnPM-devel/blob/master/snpm_pi_TwoSampT.m#L221), is incredibly slow.

For more than, say, 2000 perms, give up, and just do a Monte Carlo permutation (with possible risk of repeated perms) and don't worry about it. (Or, maybe use [hash functions](http://www.mathworks.com/matlabcentral/fileexchange/31272-datahash) to do this more intelligently).

Thanks to @felipegb94 & co for identifying this issue.

**Comment by felipegb94** [comment]
In my snpm fork I just do it the monte carlo permutation way. I call the following function inside TwoSampT: [Monte carlo permutation relabellings](https://github.com/felipegb94/SnPM-devel/blob/master/snpm_TwoSampleTGetLabelsMatrices.m). In the runs I did there was no difference in the max null distributions produced by the monte carlo permutation compared to the while loop way. But it is important to note that the datasets I used were of 50+ subjects..

**Comment by cmaumet** [comment]
@felipegb94: would you like to send us a pull request including this edit? We could then run it against our test battery and potentially include those changes as part of the next SnPM release. Please let us know if that could be possible for you and if you need any info. Thank you!

**Comment by nicholst** [comment]
@cmaumet: We just need a conditional around the lines 221-223 for the case of many (e.g. >2000) perms, so no need to call another function.  I can create a PR shortly.

**Comment by cmaumet** [comment]
This is now implemented in https://github.com/nicholst/SnPM-devel/pull/12 to be included in the next release (cf. #15).
