### ISSUE TITLE
rand warning

### ISSUE THREAD

**Issue by nicholst** [nicholst/SnPM-devel#3]
Running current (master) branch of SnPM on SPM12 with Matlab 2013a, running a two-sample t-test, I get a complaint about our use of `seed`.  @cmaumet can you search for uses of this and update accordingly (but also note how this might make us no longer backwards compatible with older Matlab versions... just for release notes).
<pre>
Warning: Using 'seed' to set RAND's internal state causes RAND, RANDI, and RANDN to use legacy random number
generators.  This syntax will be removed in a future release.  See <a href="matlab:helpview([docroot
'\techdoc\math\math.map'],'update_random_number_generator')">Updating Your Random Number Generator Syntax</a>
to use RNG to replace the old syntax. 
> In snpm_pi_TwoSampT at 116
  In snpm_ui at 297
  In snpm_run_ui at 12
  In matlabbatch/private/cfg_run_cm at 29
  In cfg_util>local_runcj at 1673
  In cfg_util at 953
  In cfg_ui>MenuFileRun_Callback at 707
  In gui_mainfcn at 96
  In cfg_ui at 53 
</pre>

**Comment by cmaumet** [comment]
I will need to look closely into that to make sure that we do not break the test set.

**Comment by cmaumet** [comment]
@nicholst: I am looking at this now and wondering if we could just remove the random initialisation of the random number generator:
```
rand('seed',sum(100*clock));
```
I would say that it is for the user to decide if they want to use a particular seed to initialise the random generator and that SnPM itself should not overwrite it. Does that make sense?

**Comment by nicholst** [comment]
I'd say that randomness is important... i.e. different results each time.  

Let's see what SPM12 does... with the recommended `rng`...
```
spm_dcm_peb_rnd_search.m:    rng('default');
```
Oh, no much, and with `rand`
```
spm_coreg.m:rand('state',100); % rng(100,'v5uniform'); % rng('defaults');
spm_dicom_convert.m:    rand('state',0);
spm_maff8.m:    rand('seed',1);
spm_vb_graphcut.m:s = rand('twister'); rand('seed',0);
```
Oh... it doesn't change either.

Hmmm... I still think that randomness is good, and only is bad for testing.  I'd say we keep it.

**Comment by cmaumet** [comment]
> I'd say that randomness is important... i.e. different results each time.

Randomness in important. But in terms of user experience, as long as they do not restart Matlab between two runs, they will get different results each time.

> I still think that randomness is good, and only is bad for testing.

I can think of 2 additional use-cases where the user wants to be in control of the RNG:
 - *Replication* (re-obtaining the same results on the same data in the same environment) which is useful for instance to recompute published results.
 - *Cluster computing*: in that case rewriting the seed using a timestamp is not good...

**Comment by nicholst** [comment]
What about `rng('shuffle')` ... would that ensure random (unique) seeds on a HPC?

**Comment by cmaumet** [comment]
`rng('shuffle')` is also based on a timestamp so the issue would remain.

**Comment by nicholst** [comment]
What about combining time with `feature('getpid')`, like as in: http://stackoverflow.com/questions/22792495/produce-random-numbers-in-matlab-without-rng-shuffle-independent-of-system-time

You'd have to allow for `feature` to fail, e.g. as it might on a PC, but then that shouldn't be a concern for a cluster/HPC.  (BTW, I checked it works even with `-nojvm`, which I was worried about since someone wrote it was the pid of the javamachine).

**Comment by cmaumet** [comment]
The pids would be unique for a given node but I am not sure what would be the behaviour across nodes (and maybe we can avoid relying on undocumented features). 

How about:
 - using `rng('shuffle')` by default 
 - creating a parameter in [snpm_defaults.m](https://github.com/nicholst/SnPM-devel/blob/master/snpm_defaults.m) to possibly disable the initialization of the random number generator (useful for HPC, replication, tests, etc.).

?

**Comment by nicholst** [comment]
No, for distinct instance of Matlab it's fine:

![screen shot 2016-07-19 at 09 58 40](https://cloud.githubusercontent.com/assets/5155907/16944215/66696a80-4d97-11e6-9409-8b42fe863814.png)

**Comment by cmaumet** [comment]
Is this across nodes or within-node? What I meant is that pids are unique per machine but not for 2 different machines/nodes. 

So, using the pid solves the issue for 2 processes started at the same time on the same host but potentially creates a new issue for 2 processes started on different hosts. 

To create unique ids across processes we would have to combine machine&pid (maybe as in http://pid.github.io/puid/). But it is much simpler for the user to define their own seed based on the HPC job identifier. I think an HPC user should be aware of those issues and decide on how to set the seed.

How do you feel about my proposal above?

**Comment by nicholst** [comment]
I find the worry about two distinct hosts having the *same* PID starting at the *same* time excessive.  puid is cool, but is over engineering the solution.

Anyway, *yes* `rng('shuffle')` with option to disable sounds fine to me.

**Comment by cmaumet** [comment]
Great! I will implement that!

(PIDs could be identical on 2 hosts independent of the process starting time, that's not very likely, but possible...)
