### ISSUE TITLE
SnPM crashes when repeating a run launched from the batch editor

### ISSUE THREAD

**Issue by felipegb94** [nicholst/SnPM-devel#34]
Hi @cmaumet and @nicholst ,

I stumbled into the following problem when trying to create the test for RapidPT (https://github.com/nicholst/SnPM-devel/pull/28). After doing some runs with snpm I get the following output: 

```
The run took 0.07 minutes

Correct Perm has max t 29.677 & rank 1 out of 3432 completed permutations

	Run snpm_pp for full results

Done    'Compute'
The following modules did not run:
Failed: 2 Groups: Two Sample T test; 1 scan per subject
```

So it seems that snpm is able to finish the computation but throws an error at the end. To replicate the  error follow these steps:

1.  Get latest SnPM-devel/master.
2. Launch spm.
3. Open the batch editor.
4. Choose spm->tools->SnPM->specify 2 groups two samp t test
5. Pick your analysis dir, scans, and number of permutations (I chose 7 scans for each group from the SnPM_test_data and 3000 perms).
6. Run to generate the cfg file.
7. Choose spm->tools->SnPM->Compute and pick the generated config file.
8. Run

Up to this point Snpm work normally. Now after the run:

9. Go back to the batch editor and change the number of permutations (I changed it to 3100)
10. Re-run

Here snpm will run normally and fail after it finishes the computation. 

Hopefully it is an easy error to replicate.

**Comment by nicholst** [comment]
Hi @felipegb94,

Thanks for this!  This is a sporadic error but I was able to reproduce it and I *think* I've nailed it, with this PR https://github.com/nicholst/SnPM-devel/pull/39.
