### ISSUE TITLE
Refresh batch window after run

### ISSUE THREAD

**Issue by cmaumet** [nicholst/SnPM-devel#4]
Pointed out by @nicholst: the batch window should be refreshed each time the run button is hit. 

If a user does the `specify` step and runs it, he/she should then have a clear batch window before specifying and running the `compute` step.

**Comment by cmaumet** [comment]
I have just checked and this is *not* the default behaviour in SPM. For example, when a one-sample t-test is specified and run, after execution the batch editor window keeps the information on the job that was just run. 

I would tend to say that we should keep the same behaviour for SnPM and therefore close this issue. 

@nicholst: are you okay with this?

**Comment by nicholst** [comment]
Yes! This is fine... mimicking behavior of SPM is always desireable.

**Comment by cmaumet** [comment]
Great!
